/*
 * Broadcom Proprietary and Confidential. Copyright 2016 Broadcom
 * All Rights Reserved.
 *
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom Corporation;
 * the contents of this file may not be disclosed to third parties, copied
 * or duplicated in any form, in whole or in part, without the prior
 * written permission of Broadcom Corporation.
 */

/**
 * @file Apollo log routines
 */

#pragma once

#include <stdarg.h>
#include "wiced_result.h"

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************
 *                      Macros
 ******************************************************/

/******************************************************
 *                    Constants
 ******************************************************/

/******************************************************
 *                   Enumerations
 ******************************************************/

typedef enum
{
    APOLLO_LOG_OFF = 0,
    APOLLO_LOG_ERR,
    APOLLO_LOG_WARNING,
    APOLLO_LOG_NOTICE,
    APOLLO_LOG_INFO,
    APOLLO_LOG_DEBUG0,
    APOLLO_LOG_DEBUG1,
    APOLLO_LOG_DEBUG2,
    APOLLO_LOG_DEBUG3,
    APOLLO_LOG_DEBUG4,

    APOLLO_LOG_PRINTF, /* Identifies log messages generated by apollo_log_printf calls */

    APOLLO_LOG_MAX
} APOLLO_LOG_LEVEL_T;

/******************************************************
 *                 Type Definitions
 ******************************************************/

typedef int (*log_output)(APOLLO_LOG_LEVEL_T level, char *logmsg);

/******************************************************
 *                    Structures
 ******************************************************/

/******************************************************
 *               Function Declarations
 ******************************************************/

wiced_result_t  apollo_log_init(APOLLO_LOG_LEVEL_T level, log_output platform_output);
wiced_result_t  apollo_log_shutdown(void);
wiced_result_t  apollo_log_set_platform_output(log_output platform_output);
wiced_result_t  apollo_log_set_level(APOLLO_LOG_LEVEL_T level);
APOLLO_LOG_LEVEL_T apollo_log_get_level(void);
wiced_result_t  apollo_log_msg(APOLLO_LOG_LEVEL_T level, const char *fmt, ...);
wiced_result_t  apollo_log_printf(const char *fmt, ...);
wiced_result_t  apollo_log_vprintf(const char *fmt, va_list varg);

#ifdef __cplusplus
} /* extern "C" */
#endif
