#
# Copyright 2013, Broadcom Corporation
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom Corporation;
# the contents of this file may not be disclosed to third parties, copied
# or duplicated in any form, in whole or in part, without the prior
# written permission of Broadcom Corporation.
#

NAME := NetX_Duo

VERSION := 5.6

$(NAME)_COMPONENTS += Wiced/Network/NetX_Duo/wwd

ifeq (,$(APP_WWD_ONLY)$(NS_WWD_ONLY)$(RTOS_WWD_ONLY))
$(NAME)_COMPONENTS += Wiced/Network/NetX_Duo/wiced
endif

# Define some macros to allow for some network-specific checks
GLOBAL_DEFINES += NETWORK_$(NAME)=1
GLOBAL_DEFINES += $(NAME)_VERSION=$$(SLASH_QUOTE_START)v$(VERSION)$$(SLASH_QUOTE_END)

GLOBAL_INCLUDES := ver$(VERSION) \
                   wiced

VALID_RTOS_LIST:= ThreadX

# prevent sending reset for non-blocking disconnect
GLOBAL_DEFINES  += NX_INCLUDE_USER_DEFINE_FILE
GLOBAL_DEFINES  += __fd_set_defined
GLOBAL_DEFINES  += __suseconds_t_defined

ifdef WICED_ENABLE_TRACEX
$(info TRACEX)
NETX_DUO_LIBRARY_NAME :=NetX_Duo.TraceX.$(HOST_ARCH).$(BUILD_TYPE).a
else
NETX_DUO_LIBRARY_NAME :=NetX_Duo.$(HOST_ARCH).$(BUILD_TYPE).a
endif

ifneq ($(wildcard $(CURDIR)$(NETX_DUO_LIBRARY_NAME)),)
$(NAME)_PREBUILT_LIBRARY := $(NETX_DUO_LIBRARY_NAME)
else

$(NAME)_HEADERS = \
           ver$(VERSION)/nx_api.h \
           ver$(VERSION)/nx_arp.h \
           ver$(VERSION)/nx_icmp.h \
           ver$(VERSION)/nx_icmpv4.h \
           ver$(VERSION)/nx_icmpv6.h \
           ver$(VERSION)/nx_igmp.h \
           ver$(VERSION)/nx_ip.h \
           ver$(VERSION)/nx_ipv4.h \
           ver$(VERSION)/nx_ipv6.h \
           ver$(VERSION)/nx_mld.h \
           ver$(VERSION)/nx_nd_cache.h \
           ver$(VERSION)/nx_packet.h \
           ver$(VERSION)/nx_port.h \
           ver$(VERSION)/nx_rarp.h \
           ver$(VERSION)/nx_system.h \
           ver$(VERSION)/nx_tcp.h \
           ver$(VERSION)/nx_udp.h \
           ver$(VERSION)/nx_user.h \
           ver$(VERSION)/netx_bsd_layer/nxd_bsd.h \
           ver$(VERSION)/netx_applications/auto_ip/nx_auto_ip.h \
           ver$(VERSION)/netx_applications/dhcp/nxd_dhcp_client.h \
           ver$(VERSION)/netx_applications/dhcp/nxd_dhcpv6_server.h \
           ver$(VERSION)/netx_applications/dhcp/nxd_dhcpv6_client.h \
           ver$(VERSION)/netx_applications/dhcp/nxd_dhcp_server.h \
           ver$(VERSION)/netx_applications/dns/nxd_dns.h \
           ver$(VERSION)/netx_applications/ftp/nxd_ftp_client.h \
           ver$(VERSION)/netx_applications/ftp/nxd_ftp_server.h \
           ver$(VERSION)/netx_applications/ftp/filex_stub.h \
           ver$(VERSION)/netx_applications/http/nxd_http_server.h \
           ver$(VERSION)/netx_applications/http/filex_stub.h \
           ver$(VERSION)/netx_applications/http/nxd_http_client.h \
           ver$(VERSION)/netx_applications/http/nx_md5.h \
           ver$(VERSION)/netx_applications/snmp/nx_des.h \
           ver$(VERSION)/netx_applications/snmp/nxd_snmp.h \
           ver$(VERSION)/netx_applications/snmp/nx_sha1.h \
           ver$(VERSION)/netx_applications/snmp/nx_md5.h \
           ver$(VERSION)/netx_applications/sntp/nxd_sntp_client.h \
           ver$(VERSION)/netx_applications/telnet/nxd_telnet_server.h \
           ver$(VERSION)/netx_applications/telnet/nxd_telnet_client.h \
           ver$(VERSION)/netx_applications/tftp/nxd_tftp_client.h \
           ver$(VERSION)/netx_applications/tftp/filex_stub.h \
           ver$(VERSION)/netx_applications/tftp/nxd_tftp_server.h

$(NAME)_SOURCES = \
           ver$(VERSION)/nxde_icmp_enable.c \
           ver$(VERSION)/nxde_icmp_interface_ping.c \
           ver$(VERSION)/nxde_icmp_ping.c \
           ver$(VERSION)/nxde_ip_raw_packet_interface_send.c \
           ver$(VERSION)/nxde_ipv6_default_router_add.c \
           ver$(VERSION)/nxde_ipv6_default_router_delete.c \
           ver$(VERSION)/nxde_ipv6_default_router_get.c \
           ver$(VERSION)/nxde_ipv6_disable.c \
           ver$(VERSION)/nxde_ipv6_enable.c \
           ver$(VERSION)/nxde_ipv6_address_change_notify.c \
           ver$(VERSION)/nxde_ipv6_stateless_address_autoconfig_disable.c \
           ver$(VERSION)/nxde_ipv6_stateless_address_autoconfig_enable.c \
           ver$(VERSION)/nxde_ip_raw_packet_send.c \
           ver$(VERSION)/nxde_ipv6_address_delete.c \
           ver$(VERSION)/nxde_ipv6_address_get.c \
           ver$(VERSION)/nxde_ipv6_address_set.c \
           ver$(VERSION)/nxde_nd_cache_entry_delete.c \
           ver$(VERSION)/nxde_nd_cache_entry_set.c \
           ver$(VERSION)/nxde_nd_cache_hardware_address_find.c \
           ver$(VERSION)/nxde_nd_cache_invalidate.c \
           ver$(VERSION)/nxde_nd_cache_ip_address_find.c \
           ver$(VERSION)/nxde_tcp_client_socket_connect.c \
           ver$(VERSION)/nxde_tcp_socket_peer_info_get.c \
           ver$(VERSION)/nxde_udp_packet_info_extract.c \
           ver$(VERSION)/nxde_udp_socket_interface_send.c \
           ver$(VERSION)/nxd_udp_packet_info_extract.c \
           ver$(VERSION)/nxd_udp_socket_interface_send.c \
           ver$(VERSION)/nxde_udp_socket_send.c \
           ver$(VERSION)/nxde_udp_source_extract.c \
           ver$(VERSION)/nxd_icmp_enable.c \
           ver$(VERSION)/nxd_icmp_interface_ping.c \
           ver$(VERSION)/nxd_icmp_ping.c \
           ver$(VERSION)/nxd_ip_raw_packet_interface_send.c \
           ver$(VERSION)/nxd_ipv6_default_router_add.c \
           ver$(VERSION)/nxd_ipv6_default_router_add_internal.c \
           ver$(VERSION)/nxd_ipv6_default_router_delete.c \
           ver$(VERSION)/nxd_ipv6_default_router_get.c \
           ver$(VERSION)/nxd_ipv6_default_router_table_init.c \
           ver$(VERSION)/nxd_ipv6_destination_table_find_next_hop.c \
           ver$(VERSION)/nxd_ipv6_enable.c \
           ver$(VERSION)/nxd_ipv6_find_default_router_from_address.c \
           ver$(VERSION)/nxd_ipv6_find_max_prefix_length.c \
           ver$(VERSION)/nxd_ipv6_interface_find.c \
           ver$(VERSION)/nxd_ipv6_prefix_router_timer_tick.c \
           ver$(VERSION)/nxd_ipv6_raw_packet_send_internal.c \
           ver$(VERSION)/nxd_ipv6_router_lookup.c \
           ver$(VERSION)/nxd_ipv6_router_solicitation_check.c \
           ver$(VERSION)/nxd_ipv6_stateless_address_autoconfig_disable.c \
           ver$(VERSION)/nxd_ipv6_stateless_address_autoconfig_enable.c \
           ver$(VERSION)/nxd_ipv6_search_onlink.c \
           ver$(VERSION)/nxd_ip_raw_packet_send.c \
           ver$(VERSION)/nxd_ipv6_address_delete.c \
           ver$(VERSION)/nxd_ipv6_address_get.c \
           ver$(VERSION)/nxd_ipv6_address_set.c \
           ver$(VERSION)/nxd_nd_cache_entry_delete.c \
           ver$(VERSION)/nxd_nd_cache_entry_set.c \
           ver$(VERSION)/nxd_nd_cache_hardware_address_find.c \
           ver$(VERSION)/nxd_nd_cache_invalidate.c \
           ver$(VERSION)/nxd_nd_cache_invalidate_internal.c \
           ver$(VERSION)/nxd_nd_cache_ip_address_find.c \
           ver$(VERSION)/nxd_tcp_client_socket_connect.c \
           ver$(VERSION)/nxd_tcp_socket_peer_info_get.c \
           ver$(VERSION)/nxd_udp_socket_send.c \
           ver$(VERSION)/nxd_udp_source_extract.c \
           ver$(VERSION)/nxe_arp_dynamic_entries_invalidate.c \
           ver$(VERSION)/nxe_arp_dynamic_entry_set.c \
           ver$(VERSION)/nxe_arp_enable.c \
           ver$(VERSION)/nxe_arp_gratuitous_send.c \
           ver$(VERSION)/nxe_arp_hardware_address_find.c \
           ver$(VERSION)/nxe_arp_info_get.c \
           ver$(VERSION)/nxe_arp_ip_address_find.c \
           ver$(VERSION)/nxe_arp_static_entries_delete.c \
           ver$(VERSION)/nxe_arp_static_entry_create.c \
           ver$(VERSION)/nxe_arp_static_entry_delete.c \
           ver$(VERSION)/nxe_icmp_enable.c \
           ver$(VERSION)/nxe_icmp_info_get.c \
           ver$(VERSION)/nxe_icmp_interface_ping6.c \
           ver$(VERSION)/nxe_icmp_ping.c \
           ver$(VERSION)/nxe_igmp_enable.c \
           ver$(VERSION)/nxe_igmp_info_get.c \
           ver$(VERSION)/nxe_igmp_loopback_disable.c \
           ver$(VERSION)/nxe_igmp_loopback_enable.c \
           ver$(VERSION)/nxe_igmp_multicast_interface_join.c \
           ver$(VERSION)/nxe_igmp_multicast_join.c \
           ver$(VERSION)/nxe_igmp_multicast_leave.c \
           ver$(VERSION)/nxe_ip_address_change_notify.c \
           ver$(VERSION)/nxe_ip_address_get.c \
           ver$(VERSION)/nxe_ip_address_set.c \
           ver$(VERSION)/nxe_ip_create.c \
           ver$(VERSION)/nxe_ip_delete.c \
           ver$(VERSION)/nxe_ip_driver_direct_command.c \
           ver$(VERSION)/nxe_ip_driver_interface_direct_command.c \
           ver$(VERSION)/nxe_ip_forwarding_disable.c \
           ver$(VERSION)/nxe_ip_forwarding_enable.c \
           ver$(VERSION)/nxe_ip_fragment_disable.c \
           ver$(VERSION)/nxe_ip_fragment_enable.c \
           ver$(VERSION)/nxe_ip_gateway_address_set.c \
           ver$(VERSION)/nxe_ip_info_get.c \
           ver$(VERSION)/nxe_ip_interface_address_get.c \
           ver$(VERSION)/nxe_ip_interface_address_set.c \
           ver$(VERSION)/nxe_ip_interface_attach.c \
           ver$(VERSION)/nxe_ip_interface_info_get.c \
           ver$(VERSION)/nxe_ip_interface_status_check.c \
           ver$(VERSION)/nxe_ip_max_payload_size_find.c \
           ver$(VERSION)/nxe_ip_raw_packet_disable.c \
           ver$(VERSION)/nxe_ip_raw_packet_enable.c \
           ver$(VERSION)/nxe_ip_raw_packet_filter_set.c \
           ver$(VERSION)/nxe_ip_raw_packet_interface_send.c \
           ver$(VERSION)/nxe_ip_raw_packet_receive.c \
           ver$(VERSION)/nxe_ip_raw_packet_send.c \
           ver$(VERSION)/nxe_ip_raw_receive_queue_max_set.c \
           ver$(VERSION)/nxe_ip_static_route_add.c \
           ver$(VERSION)/nxe_ip_static_route_delete.c \
           ver$(VERSION)/nxe_ip_status_check.c \
           ver$(VERSION)/nxe_packet_allocate.c \
           ver$(VERSION)/nxe_packet_copy.c \
           ver$(VERSION)/nxe_packet_data_append.c \
           ver$(VERSION)/nxe_packet_data_extract_offset.c \
           ver$(VERSION)/nxe_packet_data_retrieve.c \
           ver$(VERSION)/nxe_packet_length_get.c \
           ver$(VERSION)/nxe_packet_pool_create.c \
           ver$(VERSION)/nxe_packet_pool_delete.c \
           ver$(VERSION)/nxe_packet_pool_info_get.c \
           ver$(VERSION)/nxe_packet_release.c \
           ver$(VERSION)/nxe_packet_transmit_release.c \
           ver$(VERSION)/nxe_rarp_disable.c \
           ver$(VERSION)/nxe_rarp_enable.c \
           ver$(VERSION)/nxe_rarp_info_get.c \
           ver$(VERSION)/nxe_tcp_client_socket_bind.c \
           ver$(VERSION)/nxe_tcp_client_socket_connect.c \
           ver$(VERSION)/nxe_tcp_client_socket_port_get.c \
           ver$(VERSION)/nxe_tcp_client_socket_unbind.c \
           ver$(VERSION)/nxe_tcp_enable.c \
           ver$(VERSION)/nxe_tcp_free_port_find.c \
           ver$(VERSION)/nxe_tcp_info_get.c \
           ver$(VERSION)/nxe_tcp_server_socket_accept.c \
           ver$(VERSION)/nxe_tcp_server_socket_listen.c \
           ver$(VERSION)/nxe_tcp_server_socket_relisten.c \
           ver$(VERSION)/nxe_tcp_server_socket_unaccept.c \
           ver$(VERSION)/nxe_tcp_server_socket_unlisten.c \
           ver$(VERSION)/nxe_tcp_socket_bytes_available.c \
           ver$(VERSION)/nxe_tcp_socket_create.c \
           ver$(VERSION)/nxe_tcp_socket_delete.c \
           ver$(VERSION)/nxe_tcp_socket_disconnect.c \
           ver$(VERSION)/nxe_tcp_socket_disconnect_complete_notify.c \
           ver$(VERSION)/nxe_tcp_socket_establish_notify.c \
           ver$(VERSION)/nxe_tcp_socket_info_get.c \
           ver$(VERSION)/nxe_tcp_socket_mss_get.c \
           ver$(VERSION)/nxe_tcp_socket_mss_peer_get.c \
           ver$(VERSION)/nxe_tcp_socket_mss_set.c \
           ver$(VERSION)/nxe_tcp_socket_peer_info_get.c \
           ver$(VERSION)/nxe_tcp_socket_receive.c \
           ver$(VERSION)/nxe_tcp_socket_receive_notify.c \
           ver$(VERSION)/nxe_tcp_socket_send.c \
           ver$(VERSION)/nxe_tcp_socket_state_wait.c \
           ver$(VERSION)/nxe_tcp_socket_timed_wait_callback.c \
           ver$(VERSION)/nxe_tcp_socket_transmit_configure.c \
           ver$(VERSION)/nxe_tcp_socket_window_update_notify_set.c \
           ver$(VERSION)/nxe_udp_enable.c \
           ver$(VERSION)/nxe_udp_free_port_find.c \
           ver$(VERSION)/nxe_udp_info_get.c \
           ver$(VERSION)/nxe_udp_packet_info_extract.c \
           ver$(VERSION)/nxe_udp_socket_bind.c \
           ver$(VERSION)/nxe_udp_socket_bytes_available.c \
           ver$(VERSION)/nxe_udp_socket_checksum_disable.c \
           ver$(VERSION)/nxe_udp_socket_checksum_enable.c \
           ver$(VERSION)/nxe_udp_socket_create.c \
           ver$(VERSION)/nxe_udp_socket_delete.c \
           ver$(VERSION)/nxe_udp_socket_info_get.c \
           ver$(VERSION)/nxe_udp_socket_interface_send.c \
           ver$(VERSION)/nxe_udp_socket_port_get.c \
           ver$(VERSION)/nxe_udp_socket_receive.c \
           ver$(VERSION)/nxe_udp_socket_receive_notify.c \
           ver$(VERSION)/nxe_udp_socket_send.c \
           ver$(VERSION)/nxe_udp_socket_unbind.c \
           ver$(VERSION)/nxe_udp_source_extract.c \
           ver$(VERSION)/nx_arp_dynamic_entries_invalidate.c \
           ver$(VERSION)/nx_arp_dynamic_entry_set.c \
           ver$(VERSION)/nx_arp_enable.c \
           ver$(VERSION)/nx_arp_entry_allocate.c \
           ver$(VERSION)/nx_arp_gratuitous_send.c \
           ver$(VERSION)/nx_arp_hardware_address_find.c \
           ver$(VERSION)/nx_arp_info_get.c \
           ver$(VERSION)/nx_arp_initialize.c \
           ver$(VERSION)/nx_arp_ip_address_find.c \
           ver$(VERSION)/nx_arp_packet_deferred_receive.c \
           ver$(VERSION)/nx_arp_packet_receive.c \
           ver$(VERSION)/nx_arp_packet_send.c \
           ver$(VERSION)/nx_arp_periodic_update.c \
           ver$(VERSION)/nx_arp_queue_process.c \
           ver$(VERSION)/nx_arp_static_entries_delete.c \
           ver$(VERSION)/nx_arp_static_entry_create.c \
           ver$(VERSION)/nx_arp_static_entry_delete.c \
           ver$(VERSION)/nx_icmpv4_packet_process.c \
           ver$(VERSION)/nx_icmpv6_DAD_clear_NDCache_entry.c \
           ver$(VERSION)/nx_icmpv6_DAD_failure.c \
           ver$(VERSION)/nx_icmpv6_dest_table_add.c \
           ver$(VERSION)/nx_icmpv6_destination_table_periodic_update.c \
           ver$(VERSION)/nx_icmpv6_dest_table_find.c \
           ver$(VERSION)/nx_icmpv6_packet_process.c \
           ver$(VERSION)/nx_icmpv6_perform_DAD.c \
           ver$(VERSION)/nx_icmpv6_process_echo_reply.c \
           ver$(VERSION)/nx_icmpv6_process_echo_request.c \
           ver$(VERSION)/nx_icmpv6_process_na.c \
           ver$(VERSION)/nx_icmpv6_process_ns.c \
           ver$(VERSION)/nx_icmpv6_process_packet_too_big.c \
           ver$(VERSION)/nx_icmpv6_process_ra.c \
           ver$(VERSION)/nx_icmpv6_process_redirect.c \
           ver$(VERSION)/nx_icmpv6_send_error_message.c \
           ver$(VERSION)/nx_icmpv6_send_ns.c \
           ver$(VERSION)/nx_icmpv6_send_queued_packets.c \
           ver$(VERSION)/nx_icmpv6_send_rs.c \
           ver$(VERSION)/nx_icmpv6_validate_neighbor_message.c \
           ver$(VERSION)/nx_icmpv6_validate_options.c \
           ver$(VERSION)/nx_icmpv6_validate_ra.c \
           ver$(VERSION)/nx_icmp_cleanup.c \
           ver$(VERSION)/nx_icmp_enable.c \
           ver$(VERSION)/nx_icmp_info_get.c \
           ver$(VERSION)/nx_icmp_interface_ping6.c \
           ver$(VERSION)/nx_icmp_packet_process.c \
           ver$(VERSION)/nx_icmp_packet_receive.c \
           ver$(VERSION)/nx_icmp_ping.c \
           ver$(VERSION)/nx_icmp_ping6.c \
           ver$(VERSION)/nx_icmp_queue_process.c \
           ver$(VERSION)/nx_igmp_enable.c \
           ver$(VERSION)/nx_igmp_info_get.c \
           ver$(VERSION)/nx_igmp_loopback_disable.c \
           ver$(VERSION)/nx_igmp_loopback_enable.c \
           ver$(VERSION)/nx_igmp_multicast_check.c \
           ver$(VERSION)/nx_igmp_multicast_interface_join.c \
           ver$(VERSION)/nx_igmp_multicast_join.c \
           ver$(VERSION)/nx_igmp_multicast_leave.c \
           ver$(VERSION)/nx_igmp_packet_process.c \
           ver$(VERSION)/nx_igmp_packet_receive.c \
           ver$(VERSION)/nx_igmp_periodic_processing.c \
           ver$(VERSION)/nx_igmp_queue_process.c \
           ver$(VERSION)/nx_invalidate_destination_entry.c \
           ver$(VERSION)/nx_ipv4_packet_receive.c \
           ver$(VERSION)/nx_ipv6_address_find_prefix.c \
           ver$(VERSION)/nx_ipv6_fragment_process.c \
           ver$(VERSION)/nx_ipv6_multicast.c \
           ver$(VERSION)/nx_ipv6_option_error.c \
           ver$(VERSION)/nx_ipv6_packet_copy.c \
           ver$(VERSION)/nx_ipv6_packet_receive.c \
           ver$(VERSION)/nx_ipv6_packet_send.c \
           ver$(VERSION)/nx_ipv6_perform_min_path_MTU_discovery.c \
           ver$(VERSION)/nx_ipv6_prefix_list_add_entry.c \
           ver$(VERSION)/nx_ipv6_prefix_list_delete.c \
           ver$(VERSION)/nx_ipv6_prefix_list_delete_entry.c \
           ver$(VERSION)/nx_ipv6_process_fragment_option.c \
           ver$(VERSION)/nx_ipv6_process_hop_by_hop_option.c \
           ver$(VERSION)/nx_ipv6_process_routing_option.c \
           ver$(VERSION)/nx_ipv6_util.c \
           ver$(VERSION)/nx_ip_address_change_notify.c \
           ver$(VERSION)/nx_ip_address_get.c \
           ver$(VERSION)/nx_ip_address_set.c \
           ver$(VERSION)/nx_ip_checksum_compute.c \
           ver$(VERSION)/nx_ip_create.c \
           ver$(VERSION)/nx_ip_suspend.c \
           ver$(VERSION)/nx_ip_resume.c \
           ver$(VERSION)/nx_ip_delete.c \
           ver$(VERSION)/nx_ip_delete_queue_clear.c \
           ver$(VERSION)/nx_ip_dispatch_process.c \
           ver$(VERSION)/nx_ip_driver_deferred_enable.c \
           ver$(VERSION)/nx_ip_driver_deferred_processing.c \
           ver$(VERSION)/nx_ip_driver_deferred_receive.c \
           ver$(VERSION)/nx_ip_driver_direct_command.c \
           ver$(VERSION)/nx_ip_driver_interface_direct_command.c \
           ver$(VERSION)/nx_ip_fast_periodic_timer_entry.c \
           ver$(VERSION)/nx_ip_forwarding_disable.c \
           ver$(VERSION)/nx_ip_forwarding_enable.c \
           ver$(VERSION)/nx_ip_forward_packet_process.c \
           ver$(VERSION)/nx_ip_fragment_assembly.c \
           ver$(VERSION)/nx_ip_fragment_disable.c \
           ver$(VERSION)/nx_ip_fragment_enable.c \
           ver$(VERSION)/nx_ip_fragment_packet.c \
           ver$(VERSION)/nx_ip_fragment_timeout_check.c \
           ver$(VERSION)/nx_ip_gateway_address_set.c \
           ver$(VERSION)/nx_ip_info_get.c \
           ver$(VERSION)/nx_ip_initialize.c \
           ver$(VERSION)/nx_ip_interface_address_get.c \
           ver$(VERSION)/nx_ip_interface_address_set.c \
           ver$(VERSION)/nx_ip_interface_attach.c \
           ver$(VERSION)/nx_ip_interface_info_get.c \
           ver$(VERSION)/nx_ip_interface_status_check.c \
           ver$(VERSION)/nx_ip_max_payload_size_find.c \
           ver$(VERSION)/nx_ip_packet_deferred_receive.c \
           ver$(VERSION)/nx_ip_packet_receive.c \
           ver$(VERSION)/nx_ip_packet_send.c \
           ver$(VERSION)/nx_ip_periodic_timer_entry.c \
           ver$(VERSION)/nx_ip_raw_packet_cleanup.c \
           ver$(VERSION)/nx_ip_raw_packet_disable.c \
           ver$(VERSION)/nx_ip_raw_packet_enable.c \
           ver$(VERSION)/nx_ip_raw_packet_filter_set.c \
           ver$(VERSION)/nx_ip_raw_receive_queue_max_set.c \
           ver$(VERSION)/nx_ip_raw_packet_interface_send.c \
           ver$(VERSION)/nx_ip_raw_packet_processing.c \
           ver$(VERSION)/nx_ip_raw_packet_receive.c \
           ver$(VERSION)/nx_ip_raw_packet_send.c \
           ver$(VERSION)/nx_ip_route_find.c \
           ver$(VERSION)/nx_ip_static_route_add.c \
           ver$(VERSION)/nx_ip_static_route_delete.c \
           ver$(VERSION)/nx_ip_static_route_find.c \
           ver$(VERSION)/nx_ip_status_check.c \
           ver$(VERSION)/nx_ip_thread_entry.c \
           ver$(VERSION)/nx_nd_cache_add.c \
           ver$(VERSION)/nx_nd_cache_add_entry.c \
           ver$(VERSION)/nx_nd_cache_clear_IsRouter_field.c \
           ver$(VERSION)/nx_nd_cache_delete_internal.c \
           ver$(VERSION)/nx_nd_cache_fast_periodic_update.c \
           ver$(VERSION)/nx_nd_cache_find_entry.c \
           ver$(VERSION)/nx_nd_cache_find_entry_by_mac_addr.c \
           ver$(VERSION)/nx_nd_cache_init.c \
           ver$(VERSION)/nx_nd_cache_slow_periodic_update.c \
           ver$(VERSION)/nx_packet_allocate.c \
           ver$(VERSION)/nx_packet_copy.c \
           ver$(VERSION)/nx_packet_data_append.c \
           ver$(VERSION)/nx_packet_data_extract_offset.c \
           ver$(VERSION)/nx_packet_data_retrieve.c \
           ver$(VERSION)/nx_packet_length_get.c \
           ver$(VERSION)/nx_packet_pool_cleanup.c \
           ver$(VERSION)/nx_packet_pool_create.c \
           ver$(VERSION)/nx_packet_pool_delete.c \
           ver$(VERSION)/nx_packet_pool_info_get.c \
           ver$(VERSION)/nx_packet_pool_initialize.c \
           ver$(VERSION)/nx_packet_release.c \
           ver$(VERSION)/nx_packet_transmit_release.c \
           ver$(VERSION)/nx_rarp_disable.c \
           ver$(VERSION)/nx_rarp_enable.c \
           ver$(VERSION)/nx_rarp_info_get.c \
           ver$(VERSION)/nx_rarp_packet_deferred_receive.c \
           ver$(VERSION)/nx_rarp_packet_receive.c \
           ver$(VERSION)/nx_rarp_packet_send.c \
           ver$(VERSION)/nx_rarp_periodic_update.c \
           ver$(VERSION)/nx_rarp_queue_process.c \
           ver$(VERSION)/nx_system_initialize.c \
           ver$(VERSION)/nx_tcp_cleanup_deferred.c \
           ver$(VERSION)/nx_tcp_client_bind_cleanup.c \
           ver$(VERSION)/nx_tcp_client_socket_bind.c \
           ver$(VERSION)/nx_tcp_client_socket_connect.c \
           ver$(VERSION)/nx_tcp_client_socket_port_get.c \
           ver$(VERSION)/nx_tcp_client_socket_unbind.c \
           ver$(VERSION)/nx_tcp_connect_cleanup.c \
           ver$(VERSION)/nx_tcp_deferred_cleanup_check.c \
           ver$(VERSION)/nx_tcp_disconnect_cleanup.c \
           ver$(VERSION)/nx_tcp_enable.c \
           ver$(VERSION)/nx_tcp_suspend.c \
           ver$(VERSION)/nx_tcp_resume.c \
           ver$(VERSION)/nx_tcp_fast_periodic_processing.c \
           ver$(VERSION)/nx_tcp_free_port_find.c \
           ver$(VERSION)/nx_tcp_info_get.c \
           ver$(VERSION)/nx_tcp_initialize.c \
           ver$(VERSION)/nx_tcp_mss_option_get.c \
           ver$(VERSION)/nx_tcp_no_connection_reset.c \
           ver$(VERSION)/nx_tcp_packet_process.c \
           ver$(VERSION)/nx_tcp_packet_receive.c \
           ver$(VERSION)/nx_tcp_packet_send_ack.c \
           ver$(VERSION)/nx_tcp_packet_send_fin.c \
           ver$(VERSION)/nx_tcp_packet_send_rst.c \
           ver$(VERSION)/nx_tcp_packet_send_syn.c \
           ver$(VERSION)/nx_tcp_periodic_processing.c \
           ver$(VERSION)/nx_tcp_queue_process.c \
           ver$(VERSION)/nx_tcp_receive_cleanup.c \
           ver$(VERSION)/nx_tcp_server_socket_accept.c \
           ver$(VERSION)/nx_tcp_server_socket_listen.c \
           ver$(VERSION)/nx_tcp_server_socket_relisten.c \
           ver$(VERSION)/nx_tcp_server_socket_unaccept.c \
           ver$(VERSION)/nx_tcp_server_socket_unlisten.c \
           ver$(VERSION)/nx_tcp_socket_bytes_available.c \
           ver$(VERSION)/nx_tcp_socket_connection_reset.c \
           ver$(VERSION)/nx_tcp_socket_create.c \
           ver$(VERSION)/nx_tcp_socket_delete.c \
           ver$(VERSION)/nx_tcp_socket_disconnect.c \
           ver$(VERSION)/nx_tcp_socket_disconnect_complete_notify.c \
           ver$(VERSION)/nx_tcp_socket_establish_notify.c \
           ver$(VERSION)/nx_tcp_socket_info_get.c \
           ver$(VERSION)/nx_tcp_socket_mss_get.c \
           ver$(VERSION)/nx_tcp_socket_mss_peer_get.c \
           ver$(VERSION)/nx_tcp_socket_mss_set.c \
           ver$(VERSION)/nx_tcp_socket_packet_process.c \
           ver$(VERSION)/nx_tcp_socket_peer_info_get.c \
           ver$(VERSION)/nx_tcp_socket_receive.c \
           ver$(VERSION)/nx_tcp_socket_receive_notify.c \
           ver$(VERSION)/nx_tcp_socket_receive_queue_flush.c \
           ver$(VERSION)/nx_tcp_socket_send.c \
           ver$(VERSION)/nx_tcp_socket_send_internal.c \
           ver$(VERSION)/nx_tcp_socket_state_ack_check.c \
           ver$(VERSION)/nx_tcp_socket_state_closing.c \
           ver$(VERSION)/nx_tcp_socket_state_data_check.c \
           ver$(VERSION)/nx_tcp_socket_state_established.c \
           ver$(VERSION)/nx_tcp_socket_state_fin_wait1.c \
           ver$(VERSION)/nx_tcp_socket_state_fin_wait2.c \
           ver$(VERSION)/nx_tcp_socket_state_last_ack.c \
           ver$(VERSION)/nx_tcp_socket_state_syn_received.c \
           ver$(VERSION)/nx_tcp_socket_state_syn_sent.c \
           ver$(VERSION)/nx_tcp_socket_state_transmit_check.c \
           ver$(VERSION)/nx_tcp_socket_state_wait.c \
           ver$(VERSION)/nx_tcp_socket_thread_resume.c \
           ver$(VERSION)/nx_tcp_socket_thread_suspend.c \
           ver$(VERSION)/nx_tcp_socket_timed_wait_callback.c \
           ver$(VERSION)/nx_tcp_socket_transmit_configure.c \
           ver$(VERSION)/nx_tcp_socket_transmit_queue_flush.c \
           ver$(VERSION)/nx_tcp_socket_window_update_notify_set.c \
           ver$(VERSION)/nx_tcp_transmit_cleanup.c \
           ver$(VERSION)/nx_tcp_window_scaling_option_get.c \
           ver$(VERSION)/nx_trace_event_insert.c \
           ver$(VERSION)/nx_trace_event_update.c \
           ver$(VERSION)/nx_trace_object_register.c \
           ver$(VERSION)/nx_trace_object_unregister.c \
           ver$(VERSION)/nx_udp_bind_cleanup.c \
           ver$(VERSION)/nx_udp_enable.c \
           ver$(VERSION)/nx_udp_free_port_find.c \
           ver$(VERSION)/nx_udp_info_get.c \
           ver$(VERSION)/nx_udp_packet_info_extract.c \
           ver$(VERSION)/nx_udp_packet_receive.c \
           ver$(VERSION)/nx_udp_receive_cleanup.c \
           ver$(VERSION)/nx_udp_socket_bind.c \
           ver$(VERSION)/nx_udp_socket_bytes_available.c \
           ver$(VERSION)/nx_udp_socket_checksum_disable.c \
           ver$(VERSION)/nx_udp_socket_checksum_enable.c \
           ver$(VERSION)/nx_udp_socket_create.c \
           ver$(VERSION)/nx_udp_socket_delete.c \
           ver$(VERSION)/nx_udp_socket_info_get.c \
           ver$(VERSION)/nx_udp_socket_interface_send.c \
           ver$(VERSION)/nx_udp_socket_port_get.c \
           ver$(VERSION)/nx_udp_socket_receive.c \
           ver$(VERSION)/nx_udp_socket_receive_notify.c \
           ver$(VERSION)/nx_udp_socket_send.c \
           ver$(VERSION)/nx_udp_socket_unbind.c \
           ver$(VERSION)/nx_udp_source_extract.c \
           ver$(VERSION)/netx_applications/dhcp/nxd_dhcp_client.c \
           ver$(VERSION)/netx_applications/dhcp/nxd_dhcp_server.c \
           ver$(VERSION)/netx_applications/dhcp/nxd_dhcpv6_client.c \
           ver$(VERSION)/netx_applications/dhcp/nxd_dhcpv6_server.c \
           ver$(VERSION)/netx_applications/dns/nxd_dns.c \
           ver$(VERSION)/netx_applications/ftp/nxd_ftp_client.c \
           ver$(VERSION)/netx_applications/ftp/nxd_ftp_server.c \
           ver$(VERSION)/netx_applications/http/nxd_http_client.c \
           ver$(VERSION)/netx_applications/http/nxd_http_server.c \
           ver$(VERSION)/netx_applications/snmp/nx_des.c \
           ver$(VERSION)/netx_applications/snmp/nx_md5.c \
           ver$(VERSION)/netx_applications/snmp/nx_sha1.c \
           ver$(VERSION)/netx_applications/snmp/nxd_snmp.c \
           ver$(VERSION)/netx_applications/sntp/nxd_sntp_client.c \
           ver$(VERSION)/netx_applications/telnet/nxd_telnet_client.c \
           ver$(VERSION)/netx_applications/telnet/nxd_telnet_server.c \
           ver$(VERSION)/netx_applications/tftp/nxd_tftp_client.c \
           ver$(VERSION)/netx_applications/tftp/nxd_tftp_server.c \
           ver$(VERSION)/netx_applications/auto_ip/nx_auto_ip.c \
           ver$(VERSION)/netx_bsd_layer/nxd_bsd.c \
           ver$(VERSION)/nxd_multicast_interface_join.c \
           ver$(VERSION)/nxd_multicast_interface_leave.c \
           ver$(VERSION)/nxde_multicast_interface_join.c \
           ver$(VERSION)/nxde_multicast_interface_leave.c

endif #ifneq ($(wildcard $(CURDIR)NetX_Duo.$(HOST_ARCH).$(BUILD_TYPE).a),)